version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: saudeIAmysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: body
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
