version: '3.8'

networks:
  minha_rede:

services:
  mysql:
    image: mysql:latest
    container_name: saudeIAmysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: SAUDEIA
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    networks:
      - minha_rede
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência de dados

  web:
    build: .
    container_name: saudeIAapp
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - minha_rede

volumes:
  mysql_data:
    driver: local

