# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SaudeIA20250315230541

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://saudeia20250315230643.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a41cd424e52a4320bc7a0ce33ef6d431 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_04227e32ed4c45fea77e9c4e85204288 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: saudeia20250315230643.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a41cd424e52a4320bc7a0ce33ef6d431 }}/saudeia:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SaudeIA20250315230541'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d51575ba3a274bd295668f323f0a2f24 }}
        images: 'saudeia20250315230643.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a41cd424e52a4320bc7a0ce33ef6d431 }}/saudeia:${{ github.sha }}'